#this is a bsic workflow to help get started with actions
name: MLOps Test with GitHub Actions
#control when workflow eill run
#trigger the workflow on push
on: [push]

#a workflow run is made up of one or more jobs taht can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{matrix.python-version}}
      uses: action/setup-python@v3
      with:
        python-version: 3.8
      
      
    - name: Install dependencies
      run: |
         make install

    - name: check the python code  # Run check
      run: |
         make lint

    - name: run unit test
      run: |
         make test
